### ISSUE TITLE
Missing thirdpartylibs.xml file.

### ISSUE THREAD

**Issue by danmarsden** [jguille2/SnapInMoodle#1]
When including an external library in your plugin, you must include a thirdpartylibs.xml file that includes the name, location and license of the library.
More information on this is here:
https://docs.moodle.org/dev/Plugin_files#thirdpartylibs.xml
And here:
https://docs.moodle.org/dev/Plugin_with_third_party_libraries

One of the other advantages of using this is that Moodle's codechecker automatically ignores any files included in the location specificed in the thirdpartylibs.xml file.

Please note - this is typically a blocker for approval in the plugins db.

**Comment by danmarsden** [comment]
hmm - looks like it is there... just looking in the wrong place because you have everything "bundled" in one git repo.

**Comment by jguille2** [comment]
Thanks @danmarsden for your report,

I'll try to document this more clearly to avoid confusion.

Yes really, this is not a "Moodle plugin repo", this is a **plugin builder repo**. The "plugin skeleton" is the "snapPlugin" folder. But some info (like the thirdpartylibs version) is not into that skeleton, is really into the **build** script, and also related to **sources** folder.

Maybe this is confusing, but I tried to do my best. There are two reasons, beyond the simple idea of making 4 plugins at once.
  - The first is to avoid *code repetition* and *lighter maintenance*. Apart from bugs, ordinary maintenance will be only updating sources, to offer plugins with the latest Snap!s versions.
  - The other reason is to document it, allowing everybody to build their own Snap! distro plugin. Yes, there are different projects using Snap! modifications. And the idea is not only to hack the original plugin. It is also to allow to have different submissions (and so, different plugins) in the same assignment.

Thanks,
Joan

**Comment by danmarsden** [comment]
I haven't gone digging yet but I did wonder why you needed this to be 4 separate plugins and didnt just add one moodle plugin with some settings to allow the user to choose which snap plugins to enable along with some form of tool that allows other snap plugins to be installed into the single moodle version(like h5p does)

**Comment by jguille2** [comment]
Thanks again @danmarsden 

I will take this into consideration.
I comment on the initial approach:
  - These plugins embed a Snap! environmment into Moodle. To do it, we need to put into each plugin the "full environment". Its the only way (at this moment) to  do it, because we have to use de JS code of this environment (iframing an external domain is not possible). Then, each "distro" adds extra 100MB to the plugin and offer an extra service (you can use each distro from your server by URL outside Moodle) that maybe is not needed (or wanted).
  - Initially, I want to make only "the Snap! submissions plugin". Everybody could hack it and play with their own Snap! distro. But also we wanted to make it easy (drag and drop and install). Then the idea is offering these 4 plugins, with the most used versions and also that builder to make customizations.
  - So, current state is a balance for different situations. We are not offering a service (depending on other web projects), just open software to be installed. Some will install one of these official plugins, others will install more than one, and others will push their own their modifications (which is what they are already doing, how much they work with Snap! outside of Moodle).

We’ll see how people use it and we’ll be able to make design change decisions.

Joan
