### ISSUE TITLE
Is it really needed to have the "run" separately in all plugins?

### ISSUE THREAD

**Issue by mudrd8mz** [jguille2/SnapInMoodle#2]
As far as I can see, all the generated plugins have the upstream Snap! library in their "run" folder. My impression is that it is the same upstream library, just different version and with different plugins included?

If so, is it really needed to have it shipped independently in each plugin? I noticed it makes the plugin ZIP pretty big (around 90MB each) which causes issues when attempting to unzip and install them via Moodle's native archiver (MDLSITE-6129).

Would it be better / wiser to distribute the Snap! upstream library as a separate standalone plugin, which all other plugins would require as a dependency?

**Comment by jguille2** [comment]
Thanks David @mudrd8mz 

Yes, all that sources has a "Snap core". But that core is not exactly the same. Snap4Arduino could be (it use "decorators" to change Snap core functions) but the others not.

Anyway, I think this is the first step to start playing Snap in Moodle and we can do more changes. Here, the plugin has its own snap distro. And this was the only solution because we couldn't "use" the JS code of the iframe of an external domain. But we are working in Snap! to add an API to do it and then, using `postMessage` we can change it.
So I guess next version we can have a very light plugin where admins can select resources (just writing URLs of those online projects). And then, this SnapInMoodle will be only for people who want to build their own distro, and we won't need different "official" plugins.

Thanks again,

Joan
