### ISSUE TITLE
Backup in Moodle 3.10.1 fails

### ISSUE THREAD

**Issue by mattgig** [jguille2/SnapInMoodle#3]
When you install Snap4Arduino in Moodle 3.10.1, make an assignment using the plugin and try to backup your couse, Moodle throws the following error:

Table "assignsubmission_snap4arduino" does not exist

Thus, you won't be able to backup your couse anymore until to deinstall the plugin.

**Comment by jguille2** [comment]
Hi Mattias @mattgig 

It's strange. I'm re-testing now over Moodle 3.9 and backups are running ok.
I'll test over 3.10  later to see... But it's also strange, because that table is really created (and needed) when plugin is installed.

I will comment later... but, to have more info and reproduce your issue, some questions:
  - Have you installed only **Snap4Arduino submissions plugin** (https://moodle.org/plugins/assignsubmission_snap4arduino) or you have installed also other "snaps" submissions plugins (Snap! or Beetleblocks...)
  - Have you installed it from the Moodle repo, or from this *github releases area*, or have you built your own plugin from our source?

Continue,

Joan

**Comment by mattgig** [comment]
Hi Joan

I have installed the plugin from the Moodle Plugin Repository, not from Github.

In my main installation I had first only installed the Snap! plugin and came across the backup probelm after I installed Snap4Arduino. Once you deinstall it again, the manual backup starts working again.

Because I was suspicious that another plugin could cause the problem, I've installed Snap4Arduino on a second instance of Moodle, also 3.10.1 which I use for testing purposes and is mostly bare-bone. The moment you have Snap4Arduino installed, the exactly same error message appears.

In case you need further details, I'm happy to provide them.

Regards
Matthias

**Comment by jguille2** [comment]
Hi Matthias @mattgig ,

Yes, I can reproduce your issue. I'm sorry.

I've tested again on Moodle310, and It was fine. And I've tested backups, running also ok.
Oh! But the problem is when the backup is "with users data"! And yes, the problem affects all Moodle versions, on Snap4Arduino, BeetleBlocks and TurtleStitch. As you said, "Snap! submissions" is fine.

I will fix this. I will update all "flavours" (also Snap! to upgrade its snap core)
Thanks for reporting this, and sorry for the problems. I will comment here to track this issue.

Joan

**Comment by jguille2** [comment]
Hi Matthias @mattgig ,

I've just released v1.1 of all four Snap!s  submission plugins.

I've fixed this _backup_ issue and also upgraded sources to last Snap!s versions.

Thanks for your report.
Your feedback will be appreciated.

https://moodle.org/plugins/assignsubmission_snap4arduino
https://github.com/jguille2/SnapInMoodle/releases/tag/v1.1

Joan

**Comment by mattgig** [comment]
Hi Joan

Thanks a lot for taking the time and dealing with the problem so quickly.

I've just run a few tests on my installation, and it seems that the issue have been solved, the backup runs through without any problems. And it works with parallel installations of Snap!4Arduino, Snap! and BeetleBlocks.

I'm also grateful that you used the opportunity to upgrade the version of Snap!

Regards
Matthias

**Comment by jguille2** [comment]
Hi Mattias @mattgig 
and thanks for testing.

Some comments (maybe useful for you):
- I want to build another "general plugin" running with a Snap! online version, to be always updated. It was not possible before because we need the "postMessage" methods added to Snap! recently.
- In the meantime, if you want to update your Snap! distro, you can do it. Just replace the "run" folder of the plugin with a newer version and it runs ok.
- About Snap4Arduino. I will work in a new Snap4Arduino web version using the new WebSerialApi. It won't need any google extension to connect  your serial devices. But now, we need our "Snap4Arduino connector" installed. And that connector only accepts our "recognized" domains.
  If you need this, you can build your own "google extension" (just with a single modification of ours). Or maybe I can build a version for school/institution.

Joan
