### ISSUE TITLE
Projects never saved / submitted

### ISSUE THREAD

**Issue by OZimmermann** [jguille2/SnapInMoodle#4]
Hello, thanks for great work. 
Unfortunately, my students cannot save their projects. 
Every time the students start Snap as an assignment, a message "Leave Website" appears. When the students then try to save, the message appears again and the student's project is not submitted to Moodle and therefore not saved. 
I am using Chrome or Brave and Moodle 3.11.

<img width="971" alt="Bildschirmfoto 2022-05-16 um 18 43 56" src="https://user-images.githubusercontent.com/82403411/168642601-9a76c3b6-277b-4658-bb46-eddadc51499a.png">
<img width="944" alt="Bildschirmfoto 2022-05-16 um 18 44 13" src="https://user-images.githubusercontent.com/82403411/168642592-0caa6c32-9e94-46a4-aad6-960877a188fd.png">

Please help
 Oliver

**Comment by jguille2** [comment]
Hi @OZimmermann  and very sorry for the late reply :(

I was overworked and also I was sure there was no clear solution, because the "hacked" javascript in the v1 of the plugin (the only I could do with Snap! 6) was fine  but it could interfere with other javascript of some moodle instances (some more complex themes or other plugins...)

And I had to rewrite the plugin with the "new" (after Snap!7) features. And I was able to do it this summer, to present it at SnapCon22.

So my suggestion is upgrading to the versions 2.1 of the plugin and all the possible javascript issues will dissapear.
[https://moodle.org/plugins/assignsubmission_snap](https://moodle.org/plugins/assignsubmission_snap)

You can see the presentation [https://www.snapcon.org/conferences/2022/program/proposals/454](https://www.snapcon.org/conferences/2022/program/proposals/454) . It's a bit cumbersome... Apart from my poor English, it was a workshop... but it does explain clearly how the plugin works.

I close this issue... and any problem, you can open another one here or directly on the [plugin support place](https://github.com/jguille2/moodle-assignsubmission_snap/issues).

Thank you for your patience and I hope you enjoy the possibilities of the plugin.

**Comment by OZimmermann** [comment]
Hello @jguille2,

thank you very much for the reply. I was already hoping that you are working on a new version and helped me with small workouts. During the vacations I had to completely renew our school server and install Moodle version 4. In the process I also found the new version of the plugin and noticed that the bugs are gone.
Monday I will use the plugin in a workshop on "AI with SNAP! In school" and recommend it to colleagues.

Thank you very much for the great work and support.
Many greetings
Oliver Zimmermann

Übersetzt mit DeepL (https://www.deepl.com/app/?utm_source=ios&utm_medium=app&utm_campaign=share-translation
Am 18. Aug. 2022, 14:25 +0200 schrieb Joan Guillén i Pelegay ***@***.***>:
